[
//UNIFORMS
"TAC_CW_HS_WT_ATT_Camo",
"TAC_CW_SS_WT_ATT_Camo",

//HELMETS
"TACCW_Airframe_ATT",
"TACCW_Beanie_ATT",
"TACCW_Boonie_ATT",
"TACCW_Cap_ATT",
"TACCW_Cap_Comms_ATT",
"TACCW_FAST_B_ATT",
"TACCW_FAST_C_ATT",
"TACCW_MICH_B_ATT",
"TACCW_MICH_C_ATT",
"TACCW_Cap_Patrol_ATT",
"TACCW_Cap_Back_ATT",
"TACCW_Cap_Comms_Back_ATT",

//VESTS
"CIRAS_ATT_Assaulter_Belt",
"CIRAS_ATT_grenadier_Belt",
"CIRAS_ATT_Gunner_Belt",
"CIRAS_ATT_marksman_Belt",
"CIRAS_ATT_medic_Belt",
"CIRAS_ATT_TeamLeader_Belt",
"JPC_ATT_Assaulter_Belt",
"JPC_ATT_Grenadier_Belt",
"JPC_ATT_Gunner_Belt",
"JPC_ATT_Marksman_Belt",
"JPC_ATT_Medic_Belt",
"JPC_ATT_Teamleader_Belt",
"MBAV_ATT_Assaulter",
"MBAV_ATT_Grenadier",
"MBAV_ATT_Gunner",
"MBAV_ATT_Medic",
"MMAC_ATT_Assaulter_Belt",
"MMAC_ATT_Grenadier_Belt",
"MMAC_ATT_Gunner_Belt",
"MMAC_ATT_Marksman_Belt",
"MMAC_ATT_Medic_Belt",
"MMAC_ATT_TeamLeader_Belt",

//BACKPACKS
"TACCW_ATT_Backpack_Assault",
"TACCW_ATT_bergen",
"TACCW_ATT_carryall",
"TACCW_ATT_Backpack_Kitbag",
"Patrol_ATT",
"Panel_Breacher_ATT",
"Panel_Hydration_ATT",
"Panel_Pointman_ATT",
"Panel_Tomahawk_ATT",

//FACEWEAR
"Face_ATT",
"Face_Shemagh_Goggles_ATT",
"Face_Goggles_ATT",
"Face_Shemagh_Shades_ATT",
"Face_Shades_ATT",
"Face_Shemagh_ATT"
]